### ISSUE TITLE
https://developer.mozilla.org/en-US/docs/MDN/Feedback

### ISSUE THREAD

**Issue by albertkingori** [mdn/sprints#1882]
# Request type

- [x] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [ ] Correction or update

# Details

i cannot connect to the mongoDb atlas ie  i get the following errors
C:\Users\Albert\express-locallibrary-tutorial>node populatedb "mongodb+srv://alb
ert: 9323525akM@cluster0-dcebd.mongodb.net/local_library?retryWrites=true&w=majo
rity"
This script populates some test books, authors, genres and bookinstances to your
 database. Specified database as argument - e.g.: populatedb mongodb+srv://coolu
ser:coolpassword@cluster0-mbdj7.mongodb.net/local_library?retryWrites=true
MongoDB connection error: { MongoNetworkError: failed to connect to server [clus
ter0-shard-00-00-dcebd.mongodb.net:27017] on first connect [MongoError: bad auth
 Authentication failed.]
    at Pool.<anonymous> (C:\Users\Albert\express-locallibrary-tutorial\node_modu
les\mongodb-core\lib\topologies\server.js:431:11)
    at Pool.emit (events.js:198:13)
    at connect (C:\Users\Albert\express-locallibrary-tutorial\node_modules\mongo
db-core\lib\connection\pool.js:557:14)
    at callback (C:\Users\Albert\express-locallibrary-tutorial\node_modules\mong
odb-core\lib\connection\connect.js:109:5)
    at provider.auth.err (C:\Users\Albert\express-locallibrary-tutorial\node_mod
ules\mongodb-core\lib\connection\connect.js:352:21)
    at _authenticateSingleConnection (C:\Users\Albert\express-locallibrary-tutor
ial\node_modules\mongodb-core\lib\auth\auth_provider.js:66:11)
    at sendAuthCommand (C:\Users\Albert\express-locallibrary-tutorial\node_modul
es\mongodb-core\lib\auth\scram.js:215:18)
    at Connection.messageHandler (C:\Users\Albert\express-locallibrary-tutorial\
node_modules\mongodb-core\lib\connection\connect.js:334:5)
    at Connection.emit (events.js:198:13)
    at processMessage (C:\Users\Albert\express-locallibrary-tutorial\node_module
s\mongodb-core\lib\connection\connection.js:364:10)
    at TLSSocket.<anonymous> (C:\Users\Albert\express-locallibrary-tutorial\node
_modules\mongodb-core\lib\connection\connection.js:533:15)
    at TLSSocket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at TLSSocket.Readable.push (_stream_readable.js:224:10)
    at TLSWrap.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
  name: 'MongoNetworkError',
  errorLabels: [ 'TransientTransactionError' ],
  [Symbol(mongoErrorContextSymbol)]: {} }
(node:3344) UnhandledPromiseRejectionWarning: MongoNetworkError: failed to conne
ct to server [cluster0-shard-00-00-dcebd.mongodb.net:27017] on first connect [Mo
ngoError: bad auth Authentication failed.]
    at Pool.<anonymous> (C:\Users\Albert\express-locallibrary-tutorial\node_modu
les\mongodb-core\lib\topologies\server.js:431:11)
    at Pool.emit (events.js:198:13)
    at connect (C:\Users\Albert\express-locallibrary-tutorial\node_modules\mongo
db-core\lib\connection\pool.js:557:14)
    at callback (C:\Users\Albert\express-locallibrary-tutorial\node_modules\mong
odb-core\lib\connection\connect.js:109:5)
    at provider.auth.err (C:\Users\Albert\express-locallibrary-tutorial\node_mod
ules\mongodb-core\lib\connection\connect.js:352:21)
    at _authenticateSingleConnection (C:\Users\Albert\express-locallibrary-tutor
ial\node_modules\mongodb-core\lib\auth\auth_provider.js:66:11)
    at sendAuthCommand (C:\Users\Albert\express-locallibrary-tutorial\node_modul
es\mongodb-core\lib\auth\scram.js:215:18)
    at Connection.messageHandler (C:\Users\Albert\express-locallibrary-tutorial\
node_modules\mongodb-core\lib\connection\connect.js:334:5)
    at Connection.emit (events.js:198:13)
    at processMessage (C:\Users\Albert\express-locallibrary-tutorial\node_module
s\mongodb-core\lib\connection\connection.js:364:10)
    at TLSSocket.<anonymous> (C:\Users\Albert\express-locallibrary-tutorial\node
_modules\mongodb-core\lib\connection\connection.js:533:15)
    at TLSSocket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at TLSSocket.Readable.push (_stream_readable.js:224:10)
    at TLSWrap.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
(node:3344) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
error originated either by throwing inside of an async function without a catch
block, or by rejecting a promise which was not handled with .catch(). (rejection
 id: 1)
(node:3344) [DEP0018] DeprecationWarning: Unhandled promise rejections are depre
cated. In the future, promise rejections that are not handled will terminate the
 Node.js process with a non-zero exit code.

C:\Users\Albert\express-locallibrary-tutorial>

**Comment by jasonandmonte** [comment]
I was able to resolve the error by removing the space after the username/colon.
node populatedb 'mongodb+srv://albert:9323525akM@cluster0-dcebd.mongodb.net/local_library?retryWrites=true&w=majority'

**Comment by chrisdavidmills** [comment]
Cool, I'm glad you got this to work. I had a brief look, but is there anywhere in our tutorials that got this wrong, and needs to be updated?
